PL/TimeSheet.PL.WebApplication/ViewModels/Clients/AccordionItemsPartialViewModel.cs
using System;
using System.Collections.Generic;
using TimeSheet.Shared.Models.Interfaces;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class AccordionItemsPartialViewModel
    {
        public ClientFormPartialViewModel ClientFormPartialViewModel { get; } = new ClientFormPartialViewModel();
        public IEnumerable<IClient> Clients { get; set; } = new List<IClient>();
        public Guid? InvalidClientId { get; set; }
    }
}

PL/TimeSheet.PL.WebApplication/ViewModels/Clients/BaseFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TimeSheet.PL.WebApplication.ViewModels.Shared;
using TimeSheet.Shared.Models.Interfaces;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class BaseFormViewModel
    {
        public IEnumerable<ICountry> Countries { get; set; }
        public IClient Client { get; set; } = new UpdateClientViewModel();
    }
}

PL/TimeSheet.PL.WebApplication/ViewModels/Clients/ClientFormPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class ClientFormPartialViewModel : BaseFormViewModel
    {
        public bool IsClientValid { get; set; }
        public string Message { get; set; }
    }
}

PL/TimeSheet.PL.WebApplication/ViewModels/Clients/ClientsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TimeSheet.PL.WebApplication.ViewModels.Shared;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class ClientsViewModel : LayoutViewModel
    {
        public AccordionItemsPartialViewModel AccordionItemsPartialViewModel { get; } = new AccordionItemsPartialViewModel();
        public CreateClientDialogPartialViewModel CreateClientDialogPartialViewModel { get; } = new CreateClientDialogPartialViewModel();
        public FilterLettersPartialViewModel FilterLettersPartialViewModel { get; } = new FilterLettersPartialViewModel();
        public PaginationPartialViewModel PaginationPartialViewModel { get; } = new PaginationPartialViewModel();

        public ClientsViewModel()
        {
            HeaderViewModel.NavbarViewModel.ActiveItem = NavbarViewModel.NavItems.Clients;
        }
    }
}

PL/TimeSheet.PL.WebApplication/ViewModels/Clients/CreateClientDialogPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class CreateClientDialogPartialViewModel : BaseFormViewModel
    {
        public bool HasValidationError { get; set; } = false;
    }
}

PL/TimeSheet.PL.WebApplication/ViewModels/Clients/FilterLettersPartialViewModel.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using TimeSheet.Shared.Models.Interfaces;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class FilterLettersPartialViewModel
    {
        public char CurrentLetter { get; set; }
        public IEnumerable<IClient> ClientList { get; set; }

        public IEnumerable<string> GetClientsInitialLetters()
            => ClientList.Select(client => client.Name.FirstOrDefault().ToString().ToUpper());

    }
}

PL/TimeSheet.PL.WebApplication/ViewModels/Clients/PaginationPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeSheet.PL.WebApplication.ViewModels.Clients
{
    public class PaginationPartialViewModel
    {
        public int CurrentPage { get; set; } = 1;
        public int PageCount { get; set; } = 1;
        public readonly int RowsPerPage = 5;
        public int RowsOffset { get; set; } = 0;
    }
}

PL/TimeSheet.PL.WebApplication/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TimeSheet.PL.WebApplication.ViewModels.Clients;
using TimeSheet.Shared.Models.Interfaces;
using TimeSheet.BLL.Service.Interfaces;
using TimeSheet.PL.WebApplication.ViewModels.Shared;

namespace TimeSheet.PL.WebApp.Controllers
{
    [RoutePrefix("clients")]
    public class ClientsController : Controller
    {
        private readonly ICountryService _countryService;
        private readonly IClientService _clientService;
        private ClientsViewModel _clientsViewModel = new ClientsViewModel();

        public ClientsController(ICountryService countryService, IClientService clientService)
        {
            _countryService = countryService;
            _clientService = clientService;
            int rowsPerPage = _clientsViewModel.PaginationPartialViewModel.RowsPerPage;

            IEnumerable<ICountry> countryList = _countryService.GetCountries();
            IEnumerable<IClient> clientList = _clientService.GetClients();
            IEnumerable<IClient> fetchedClients = _clientService.GetClientsByPaging(_clientsViewModel.PaginationPartialViewModel.RowsOffset, rowsPerPage);
            _clientsViewModel.CreateClientDialogPartialViewModel.Countries = countryList;
            _clientsViewModel.AccordionItemsPartialViewModel.ClientFormPartialViewModel.Countries = countryList;
            _clientsViewModel.AccordionItemsPartialViewModel.Clients = fetchedClients;
            _clientsViewModel.FilterLettersPartialViewModel.ClientList = clientList;
            decimal diff = (decimal)clientList.Count() / rowsPerPage;
            _clientsViewModel.PaginationPartialViewModel.PageCount = (int)Math.Ceiling(diff);
        }

        [Route("")]
        public ActionResult Index()
        {
            return View("Index", _clientsViewModel);
        }

        [Route("update")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ClientFormPartialViewModel form)
        {
            if (!ModelState.IsValid)
            {
                _clientsViewModel.AccordionItemsPartialViewModel.InvalidClientId = form.Client.Id;
                return Index();
            }
            IClient client = new UpdateClientViewModel(form.Client.Id, form.Client.Name, form.Client.Address, form.Client.City, form.Client.ZipCode, form.Client.CountryId);
            _clientService.UpdateClientById(client);

            return RedirectToAction("Index");
        }

        [Route("delete/{id}")]
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            
            bool isClientRemoved = _clientService.RemoveClientById(id);
            if (!isClientRemoved)
            {
                _clientsViewModel.AccordionItemsPartialViewModel.ClientFormPartialViewModel.Message =
                    "Client is not removed";
                return Index();
            }
            return RedirectToAction("Index");
        }

        [Route("create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateClientDialogPartialViewModel form)
        {
            if (!ModelState.IsValid)
            {
                _clientsViewModel.CreateClientDialogPartialViewModel.HasValidationError = true;
                return Index();
            }
            IClient client = new CreateClientViewModel(Guid.NewGuid(), form.Client.Name, form.Client.Address, form.Client.City, form.Client.ZipCode, form.Client.CountryId);
            _clientService.AddClient(client);
            return RedirectToAction("Index");
        }

        [Route("filteredByLetter")]
        [HttpGet]
        public ActionResult FilterByLetter(char letter)
        {
            IEnumerable<IClient> filteredList = _clientService.FilterClientsByFirstLetter(letter);
            _clientsViewModel.FilterLettersPartialViewModel.CurrentLetter = letter;
            SetClientsToViewModel(filteredList, false);
            return Index();
        }

        [Route("filterByName")]
        [HttpGet]
        public ActionResult FilterByName(string searchText)
        {
            IEnumerable<IClient> filteredList = _clientService.FilterClientsByName(searchText);
            SetClientsToViewModel(filteredList, false);
            return Index();
        }

        [Route("ShowClientForms")]
        [ChildActionOnly]
        public ActionResult ShowClientForms(Guid id)
        {
            IClient client = _clientService.GetClientById(id);
            _clientsViewModel.AccordionItemsPartialViewModel.ClientFormPartialViewModel.Client = client;
            return PartialView("ClientFormPartial", _clientsViewModel.AccordionItemsPartialViewModel.ClientFormPartialViewModel);
        }

        [Route("nextClients")]
        [HttpGet]
        public ActionResult LoadNextClients(int page)
        {
            int rowsPerPage = _clientsViewModel.PaginationPartialViewModel.RowsPerPage;
            _clientsViewModel.PaginationPartialViewModel.RowsOffset = page * rowsPerPage - rowsPerPage;
            IEnumerable<IClient> fetchedClients = _clientService.GetClientsByPaging(_clientsViewModel.PaginationPartialViewModel.RowsOffset, rowsPerPage);
            _clientsViewModel.AccordionItemsPartialViewModel.Clients = fetchedClients;
            _clientsViewModel.PaginationPartialViewModel.CurrentPage = page;
            return Index();
        }

        private void SetClientsToViewModel(IEnumerable<IClient> clientList = null, bool changeLettersTab = true)
        {
            if (clientList == null)
            {
                clientList = _clientService.GetClients();
            }
            if (changeLettersTab)
            {
                _clientsViewModel.FilterLettersPartialViewModel.ClientList = clientList;
            }
            _clientsViewModel.AccordionItemsPartialViewModel.Clients = clientList;
        }
    }
}

PL/TimeSheet.PL.WebApplication/Views/Clients/AccordionItemsPartial.cshtml
@using TimeSheet.Shared.Models.Interfaces

@model TimeSheet.PL.WebApplication.ViewModels.Clients.AccordionItemsPartialViewModel
@if (Model.Clients.Count() > 0)
{
    <div class="accordion-wrap clients">
        @foreach (IClient client in Model.Clients)
        {
            bool isClientValid = client.Id != Model.InvalidClientId;
            string style = !isClientValid ? "overflow: hidden; display: block;" : null;

            <div class="item">
                <div class="heading">
                    <span>@client.Name</span>
                    <i>+</i>
                </div>
                <div style="@style" class="details">
                    @if (isClientValid)
                    {
                        @Html.Action("ShowClientForms", "Clients", new { id = client.Id })
                    }
                    else
                    {
                        @Html.Partial("ClientFormPartial", Model.ClientFormPartialViewModel)
                    }
                </div>
            </div>
        }
    </div>
}
else
{
    <h1>There are no available clients</h1>
}

PL/TimeSheet.PL.WebApplication/Views/Clients/ClientFormPartial.cshtml
@model TimeSheet.PL.WebApplication.ViewModels.Clients.ClientFormPartialViewModel
@using (Html.BeginForm("Update", "Clients", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "Please fix the following errors.")

    <ul class="form">
        @Html.HiddenFor(m => m.Client.Id)
        <li>
            @Html.LabelFor(m => m.Client.Name, "Client name: ")
            @Html.TextBoxFor(m => m.Client.Name, new { @class = "in-text" })
            @Html.ValidationMessageFor(m => m.Client.Name)
        </li>
        <li>
            @Html.LabelFor(m => m.Client.ZipCode, "Zip/Postal code: ")
            @Html.TextBoxFor(m => m.Client.ZipCode, new { @class = "in-text" })
        </li>
    </ul>
        <ul class="form">
            <li>
                @Html.LabelFor(m => m.Client.Address, "Address: ")
                @Html.TextBoxFor(m => m.Client.Address, new { @class = "in-text" })
            </li>
            <li>
                @Html.LabelFor(m => m.Client.CountryId, "Country: ")
                @Html.DropDownListFor(m => m.Client.CountryId, Model.Countries.Select(country => new SelectListItem() { Text = country.Name, Value = country.Id.ToString(), Selected = country.Id == Model.Client.CountryId }))
            </li>
        </ul>
    <ul class="form last">
        <li>
            @Html.LabelFor(m => m.Client.City, "City: ")
            @Html.TextBoxFor(m => m.Client.City, new { @class = "in-text" })
        </li>
    </ul>

    if (Model.Message != null)
     {
        <strong>@Model.Message</strong>
     }
        <div class="buttons">
            <div class="inner">
                <button type="submit" class="btn green">Save</button>
                @Html.ActionLink("Delete", "Delete", "Clients", new { Model.Client.Id }, new { @class = "btn red" })
            </div>
        </div>
}

PL/TimeSheet.PL.WebApplication/Views/Clients/CreateClientDialogPartial.cshtml
@model TimeSheet.PL.WebApplication.ViewModels.Clients.CreateClientDialogPartialViewModel

<div id="new-member" class="new-member-inner">
    <h2>Create new client</h2>
    @using (Html.BeginForm("Create", "Clients", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "Please fix the following errors.")

        <ul class="form">
            <li>
                @Html.LabelFor(m => m.Client.Name, "Client name: ")
                @Html.TextBoxFor(m => m.Client.Name, new { @class = "in-text" })
                @Html.ValidationMessageFor(m => m.Client.Name)
            </li>
            <li>
                @Html.LabelFor(m => m.Client.Address, "Address: ")
                @Html.TextBoxFor(m => m.Client.Address, new { @class = "in-text" })
            </li>
            <li>
                @Html.LabelFor(m => m.Client.City, "City: ")
                @Html.TextBoxFor(m => m.Client.City, new { @class = "in-text" })
            </li>
            <li>
                @Html.LabelFor(m => m.Client.ZipCode, "Zip/Postal code: ")
                @Html.TextBoxFor(m => m.Client.ZipCode, new { @class = "in-text" })
            </li>
            <li>
                @Html.LabelFor(m => m.Client.CountryId, "Country: ")
                @Html.DropDownListFor(m => m.Client.CountryId, Model.Countries.Select(country => new SelectListItem() { Text = country.Name, Value = country.Id.ToString(), Selected = country.Id == Model.Client.CountryId }))
            </li>
        </ul>
        <div class="buttons">
            <div class="inner">
                <button type="submit" class="btn green">Save</button>
            </div>
        </div>
    }
</div>

@if (Model.HasValidationError)
{
    <script>
        window.onload = () => $("#CreateClient").click();
    </script>
}

PL/TimeSheet.PL.WebApplication/Views/Clients/FilterLettersPartial.cshtml
@model TimeSheet.PL.WebApplication.ViewModels.Clients.FilterLettersPartialViewModel
<div class="alpha">
    <ul>
        @for (char letter = 'A'; letter <= 'Z'; letter++)
            {
                string isLetterDisabled = Model.GetClientsInitialLetters().Contains(letter.ToString().ToUpper()) ? null : "disabled";
                string isLetterActive = Model.CurrentLetter == letter ? "active" : null;
            <li class="@isLetterDisabled @isLetterActive">
                @if (isLetterDisabled == null)
                {
                    if (isLetterActive != null)
                    {
                        @Html.ActionLink(letter.ToString(), "Index", "Clients")

                    }
                    else
                    {
                        @Html.ActionLink(letter.ToString(), "FilterByLetter", "Clients", new { letter }, null)

                    }
                }
                else
                {
                    <a href="javascript:;">@letter</a>
                }
            </li>
        }
    </ul>
</div>

PL/TimeSheet.PL.WebApplication/Views/Clients/HeaderBoxPartial.cshtml
<div class="grey-box-wrap reports">
    @Html.Partial("SearchFormPartial")
</div>

PL/TimeSheet.PL.WebApplication/Views/Clients/PaginationPartial.cshtml
@model TimeSheet.PL.WebApplication.ViewModels.Clients.PaginationPartialViewModel
<div class="pagination">
    <ul>
        @if (Model.CurrentPage != 1)
        {
            <li>
                @Html.ActionLink("Previous", "LoadNextClients", new { page = Model.CurrentPage - 1 }, null)
            </li>
        }
        @for (int currentPage = 1; currentPage <= Model.PageCount; ++currentPage)
        {
            <li>
                @if (Model.CurrentPage == currentPage)
                {
                    <a class="disabled" href="javascript:;">@currentPage</a>
                }
                else
                {
                    @Html.ActionLink(currentPage.ToString(), "LoadNextClients", new { page = currentPage }, null)
                }
            </li>
        }

        @if (Model.CurrentPage != Model.PageCount)
        {
            <li class="last">
                @Html.ActionLink("Next", "LoadNextClients", new { page = Model.CurrentPage + 1 }, null)
            </li>

        }
    </ul>
</div>

PL/TimeSheet.PL.WebApplication/Views/Clients/SearchFormPartial.cshtml
<div class="search-page">
    @using (Html.BeginForm("FilterByName", "Clients", FormMethod.Get))
    {
        @Html.TextBox("searchText", null, new { @class = "in-search", @type = "search" })
    }
</div>

PL/TimeSheet.PL.WebApplication/Views/Clients/index.cshtml
@model TimeSheet.PL.WebApplication.ViewModels.Clients.ClientsViewModel
<section class="content">
    <h2><i class="ico clients"></i>Clients</h2>
    <div class="grey-box-wrap reports">
        @Html.Partial("SearchFormPartial")
        <a id="CreateClient" href="#new-member" class="link new-member-popup">Create new client</a>
    </div>
    <div class="new-member-wrap">
        @Html.Partial("CreateClientDialogPartial", Model.CreateClientDialogPartialViewModel)
    </div>
    @Html.Partial("FilterLettersPartial", Model.FilterLettersPartialViewModel)
    @Html.Partial("AccordionItemsPartial", Model.AccordionItemsPartialViewModel)
    @Html.Partial("PaginationPartial", Model.PaginationPartialViewModel)
</section>

@section Scripts
    {
    @Scripts.Render("~/bundles/main")
}